import java.io.File

val commonOut = File("library/src/main/commonHtmlMain/com/lightningkite/kiteui/views/direct")
val jsOut = File("library/src/main/jsMain/com/lightningkite/kiteui/views/direct")

val css = listOf(
    "cssText" to "text",
    "cssFloat" to "float",
    "alignContent" to "align-content",
    "alignItems" to "align-items",
    "alignSelf" to "align-self",
    "animation" to "animation",
    "animationDelay" to "animation-delay",
    "animationDirection" to "animation-direction",
    "animationDuration" to "animation-duration",
    "animationFillMode" to "animation-fill-mode",
    "animationIterationCount" to "animation-iteration-count",
    "animationName" to "animation-name",
    "animationPlayState" to "animation-play-state",
    "animationTimingFunction" to "animation-timing-function",
    "backfaceVisibility" to "backface-visibility",
    "background" to "background",
    "backgroundAttachment" to "background-attachment",
    "backgroundClip" to "background-clip",
    "backgroundColor" to "background-color",
    "backgroundImage" to "background-image",
    "backgroundOrigin" to "background-origin",
    "backgroundPosition" to "background-position",
    "backgroundRepeat" to "background-repeat",
    "backgroundSize" to "background-size",
    "border" to "border",
    "borderBottom" to "border-bottom",
    "borderBottomColor" to "border-bottom-color",
    "borderBottomLeftRadius" to "border-bottom-left-radius",
    "borderBottomRightRadius" to "border-bottom-right-radius",
    "borderBottomStyle" to "border-bottom-style",
    "borderBottomWidth" to "border-bottom-width",
    "borderCollapse" to "border-collapse",
    "borderColor" to "border-color",
    "borderImage" to "border-image",
    "borderImageOutset" to "border-image-outset",
    "borderImageRepeat" to "border-image-repeat",
    "borderImageSlice" to "border-image-slice",
    "borderImageSource" to "border-image-source",
    "borderImageWidth" to "border-image-width",
    "borderLeft" to "border-left",
    "borderLeftColor" to "border-left-color",
    "borderLeftStyle" to "border-left-style",
    "borderLeftWidth" to "border-left-width",
    "borderRadius" to "border-radius",
    "borderRight" to "border-right",
    "borderRightColor" to "border-right-color",
    "borderRightStyle" to "border-right-style",
    "borderRightWidth" to "border-right-width",
    "borderSpacing" to "border-spacing",
    "borderStyle" to "border-style",
    "borderTop" to "border-top",
    "borderTopColor" to "border-top-color",
    "borderTopLeftRadius" to "border-top-left-radius",
    "borderTopRightRadius" to "border-top-right-radius",
    "borderTopStyle" to "border-top-style",
    "borderTopWidth" to "border-top-width",
    "borderWidth" to "border-width",
    "bottom" to "bottom",
    "boxDecorationBreak" to "box-decoration-break",
    "boxShadow" to "box-shadow",
    "boxSizing" to "box-sizing",
    "breakAfter" to "break-after",
    "breakBefore" to "break-before",
    "breakInside" to "break-inside",
    "captionSide" to "caption-side",
    "clear" to "clear",
    "clip" to "clip",
    "color" to "color",
    "columnCount" to "column-count",
    "columnFill" to "column-fill",
    "columnGap" to "column-gap",
    "columnRule" to "column-rule",
    "columnRuleColor" to "column-rule-color",
    "columnRuleStyle" to "column-rule-style",
    "columnRuleWidth" to "column-rule-width",
    "columnSpan" to "column-span",
    "columnWidth" to "column-width",
    "columns" to "columns",
    "content" to "content",
    "counterIncrement" to "counter-increment",
    "counterReset" to "counter-reset",
    "cursor" to "cursor",
    "direction" to "direction",
    "display" to "display",
    "emptyCells" to "empty-cells",
    "filter" to "filter",
    "flex" to "flex",
    "flexBasis" to "flex-basis",
    "flexDirection" to "flex-direction",
    "flexFlow" to "flex-flow",
    "flexGrow" to "flex-grow",
    "flexShrink" to "flex-shrink",
    "flexWrap" to "flex-wrap",
    "font" to "font",
    "fontFamily" to "font-family",
    "fontFeatureSettings" to "font-feature-settings",
    "fontKerning" to "font-kerning",
    "fontLanguageOverride" to "font-language-override",
    "fontSize" to "font-size",
    "fontSizeAdjust" to "font-size-adjust",
    "fontStretch" to "font-stretch",
    "fontStyle" to "font-style",
    "fontSynthesis" to "font-synthesis",
    "fontVariant" to "font-variant",
    "fontVariantAlternates" to "font-variant-alternates",
    "fontVariantCaps" to "font-variant-caps",
    "fontVariantEastAsian" to "font-variant-east-asian",
    "fontVariantLigatures" to "font-variant-ligatures",
    "fontVariantNumeric" to "font-variant-numeric",
    "fontVariantPosition" to "font-variant-position",
    "fontWeight" to "font-weight",
    "hangingPunctuation" to "hanging-punctuation",
    "height" to "height",
    "hyphens" to "hyphens",
    "imageOrientation" to "image-orientation",
    "imageRendering" to "image-rendering",
    "imageResolution" to "image-resolution",
    "imeMode" to "ime-mode",
    "justifyContent" to "justify-content",
    "left" to "left",
    "letterSpacing" to "letter-spacing",
    "lineBreak" to "line-break",
    "lineHeight" to "line-height",
    "listStyle" to "list-style",
    "listStyleImage" to "list-style-image",
    "listStylePosition" to "list-style-position",
    "listStyleType" to "list-style-type",
    "margin" to "margin",
    "marginBottom" to "margin-bottom",
    "marginLeft" to "margin-left",
    "marginRight" to "margin-right",
    "marginTop" to "margin-top",
    "mark" to "mark",
    "markAfter" to "mark-after",
    "markBefore" to "mark-before",
    "marks" to "marks",
    "marqueeDirection" to "marquee-direction",
    "marqueePlayCount" to "marquee-play-count",
    "marqueeSpeed" to "marquee-speed",
    "marqueeStyle" to "marquee-style",
    "mask" to "mask",
    "maskType" to "mask-type",
    "maxHeight" to "max-height",
    "maxWidth" to "max-width",
    "minHeight" to "min-height",
    "minWidth" to "min-width",
    "navDown" to "nav-down",
    "navIndex" to "nav-index",
    "navLeft" to "nav-left",
    "navRight" to "nav-right",
    "navUp" to "nav-up",
    "objectFit" to "object-fit",
    "objectPosition" to "object-position",
    "opacity" to "opacity",
    "order" to "order",
    "orphans" to "orphans",
    "outline" to "outline",
    "outlineColor" to "outline-color",
    "outlineOffset" to "outline-offset",
    "outlineStyle" to "outline-style",
    "outlineWidth" to "outline-width",
    "overflowWrap" to "overflow-wrap",
    "overflowX" to "overflow-x",
    "overflowY" to "overflow-y",
    "padding" to "padding",
    "paddingBottom" to "padding-bottom",
    "paddingLeft" to "padding-left",
    "paddingRight" to "padding-right",
    "paddingTop" to "padding-top",
    "pageBreakAfter" to "page-break-after",
    "pageBreakBefore" to "page-break-before",
    "pageBreakInside" to "page-break-inside",
    "perspective" to "perspective",
    "perspectiveOrigin" to "perspective-origin",
    "phonemes" to "phonemes",
    "position" to "position",
    "quotes" to "quotes",
    "resize" to "resize",
    "rest" to "rest",
    "restAfter" to "rest-after",
    "restBefore" to "rest-before",
    "right" to "right",
    "tabSize" to "tab-size",
    "tableLayout" to "table-layout",
    "textAlign" to "text-align",
    "textAlignLast" to "text-align-last",
    "textCombineUpright" to "text-combine-upright",
    "textDecoration" to "text-decoration",
    "textDecorationColor" to "text-decoration-color",
    "textDecorationLine" to "text-decoration-line",
    "textDecorationStyle" to "text-decoration-style",
    "textIndent" to "text-indent",
    "textJustify" to "text-justify",
    "textOrientation" to "text-orientation",
    "textOverflow" to "text-overflow",
    "textShadow" to "text-shadow",
    "textTransform" to "text-transform",
    "textUnderlinePosition" to "text-underline-position",
    "top" to "top",
    "transform" to "transform",
    "transformOrigin" to "transform-origin",
    "transformStyle" to "transform-style",
    "transition" to "transition",
    "transitionDelay" to "transition-delay",
    "transitionDuration" to "transition-duration",
    "transitionProperty" to "transition-property",
    "transitionTimingFunction" to "transition-timing-function",
    "unicodeBidi" to "unicode-bidi",
    "verticalAlign" to "vertical-align",
    "visibility" to "visibility",
    "voiceBalance" to "voice-balance",
    "voiceDuration" to "voice-duration",
    "voicePitch" to "voice-pitch",
    "voicePitchRange" to "voice-pitch-range",
    "voiceRate" to "voice-rate",
    "voiceStress" to "voice-stress",
    "voiceVolume" to "voice-volume",
    "whiteSpace" to "white-space",
    "widows" to "widows",
    "width" to "width",
    "wordBreak" to "word-break",
    "wordSpacing" to "word-spacing",
    "wordWrap" to "word-wrap",
    "writingMode" to "writing-mode",
    "zIndex" to "z-index",
)

val html = listOf(
    "cssText" to "String" to ("text"),
    "cssFloat" to "String" to ("float"),
    "alignContent" to "String" to ("align-content"),
    "alignItems" to "String" to ("align-items"),
    "alignSelf" to "String" to ("align-self"),
    "animation" to "String" to ("animation"),
    "animationDelay" to "String" to ("animation-delay"),
    "animationDirection" to "String" to ("animation-direction"),
    "animationDuration" to "String" to ("animation-duration"),
    "animationFillMode" to "String" to ("animation-fill-mode"),
    "animationIterationCount" to "String" to ("animation-iteration-count"),
    "animationName" to "String" to ("animation-name"),
    "animationPlayState" to "String" to ("animation-play-state"),
    "animationTimingFunction" to "String" to ("animation-timing-function"),
    "backfaceVisibility" to "String" to ("backface-visibility"),
    "background" to "String" to ("background"),
    "backgroundAttachment" to "String" to ("background-attachment"),
    "backgroundClip" to "String" to ("background-clip"),
    "backgroundColor" to "String" to ("background-color"),
    "backgroundImage" to "String" to ("background-image"),
    "backgroundOrigin" to "String" to ("background-origin"),
    "backgroundPosition" to "String" to ("background-position"),
    "backgroundRepeat" to "String" to ("background-repeat"),
    "backgroundSize" to "String" to ("background-size"),
    "border" to "String" to ("border"),
    "borderBottom" to "String" to ("border-bottom"),
    "borderBottomColor" to "String" to ("border-bottom-color"),
    "borderBottomLeftRadius" to "String" to ("border-bottom-left-radius"),
    "borderBottomRightRadius" to "String" to ("border-bottom-right-radius"),
    "borderBottomStyle" to "String" to ("border-bottom-style"),
    "borderBottomWidth" to "String" to ("border-bottom-width"),
    "borderCollapse" to "String" to ("border-collapse"),
    "borderColor" to "String" to ("border-color"),
    "borderImage" to "String" to ("border-image"),
    "borderImageOutset" to "String" to ("border-image-outset"),
    "borderImageRepeat" to "String" to ("border-image-repeat"),
    "borderImageSlice" to "String" to ("border-image-slice"),
    "borderImageSource" to "String" to ("border-image-source"),
    "borderImageWidth" to "String" to ("border-image-width"),
    "borderLeft" to "String" to ("border-left"),
    "borderLeftColor" to "String" to ("border-left-color"),
    "borderLeftStyle" to "String" to ("border-left-style"),
    "borderLeftWidth" to "String" to ("border-left-width"),
    "borderRadius" to "String" to ("border-radius"),
    "borderRight" to "String" to ("border-right"),
    "borderRightColor" to "String" to ("border-right-color"),
    "borderRightStyle" to "String" to ("border-right-style"),
    "borderRightWidth" to "String" to ("border-right-width"),
    "borderSpacing" to "String" to ("border-spacing"),
    "borderStyle" to "String" to ("border-style"),
    "borderTop" to "String" to ("border-top"),
    "borderTopColor" to "String" to ("border-top-color"),
    "borderTopLeftRadius" to "String" to ("border-top-left-radius"),
    "borderTopRightRadius" to "String" to ("border-top-right-radius"),
    "borderTopStyle" to "String" to ("border-top-style"),
    "borderTopWidth" to "String" to ("border-top-width"),
    "borderWidth" to "String" to ("border-width"),
    "bottom" to "String" to ("bottom"),
    "boxDecorationBreak" to "String" to ("box-decoration-break"),
    "boxShadow" to "String" to ("box-shadow"),
    "boxSizing" to "String" to ("box-sizing"),
    "breakAfter" to "String" to ("break-after"),
    "breakBefore" to "String" to ("break-before"),
    "breakInside" to "String" to ("break-inside"),
    "captionSide" to "String" to ("caption-side"),
    "clear" to "String" to ("clear"),
    "clip" to "String" to ("clip"),
    "color" to "String" to ("color"),
    "columnCount" to "String" to ("column-count"),
    "columnFill" to "String" to ("column-fill"),
    "columnGap" to "String" to ("column-gap"),
    "columnRule" to "String" to ("column-rule"),
    "columnRuleColor" to "String" to ("column-rule-color"),
    "columnRuleStyle" to "String" to ("column-rule-style"),
    "columnRuleWidth" to "String" to ("column-rule-width"),
    "columnSpan" to "String" to ("column-span"),
    "columnWidth" to "String" to ("column-width"),
    "columns" to "String" to ("columns"),
    "content" to "String" to ("content"),
    "counterIncrement" to "String" to ("counter-increment"),
    "counterReset" to "String" to ("counter-reset"),
    "cursor" to "String" to ("cursor"),
    "direction" to "String" to ("direction"),
    "display" to "String" to ("display"),
    "emptyCells" to "String" to ("empty-cells"),
    "filter" to "String" to ("filter"),
    "flex" to "String" to ("flex"),
    "flexBasis" to "String" to ("flex-basis"),
    "flexDirection" to "String" to ("flex-direction"),
    "flexFlow" to "String" to ("flex-flow"),
    "flexGrow" to "String" to ("flex-grow"),
    "flexShrink" to "String" to ("flex-shrink"),
    "flexWrap" to "String" to ("flex-wrap"),
    "font" to "String" to ("font"),
    "fontFamily" to "String" to ("font-family"),
    "fontFeatureSettings" to "String" to ("font-feature-settings"),
    "fontKerning" to "String" to ("font-kerning"),
    "fontLanguageOverride" to "String" to ("font-language-override"),
    "fontSize" to "String" to ("font-size"),
    "fontSizeAdjust" to "String" to ("font-size-adjust"),
    "fontStretch" to "String" to ("font-stretch"),
    "fontStyle" to "String" to ("font-style"),
    "fontSynthesis" to "String" to ("font-synthesis"),
    "fontVariant" to "String" to ("font-variant"),
    "fontVariantAlternates" to "String" to ("font-variant-alternates"),
    "fontVariantCaps" to "String" to ("font-variant-caps"),
    "fontVariantEastAsian" to "String" to ("font-variant-east-asian"),
    "fontVariantLigatures" to "String" to ("font-variant-ligatures"),
    "fontVariantNumeric" to "String" to ("font-variant-numeric"),
    "fontVariantPosition" to "String" to ("font-variant-position"),
    "fontWeight" to "String" to ("font-weight"),
    "hangingPunctuation" to "String" to ("hanging-punctuation"),
    "height" to "String" to ("height"),
    "hyphens" to "String" to ("hyphens"),
    "imageOrientation" to "String" to ("image-orientation"),
    "imageRendering" to "String" to ("image-rendering"),
    "imageResolution" to "String" to ("image-resolution"),
    "imeMode" to "String" to ("ime-mode"),
    "justifyContent" to "String" to ("justify-content"),
    "left" to "String" to ("left"),
    "letterSpacing" to "String" to ("letter-spacing"),
    "lineBreak" to "String" to ("line-break"),
    "lineHeight" to "String" to ("line-height"),
    "listStyle" to "String" to ("list-style"),
    "listStyleImage" to "String" to ("list-style-image"),
    "listStylePosition" to "String" to ("list-style-position"),
    "listStyleType" to "String" to ("list-style-type"),
    "margin" to "String" to ("margin"),
    "marginBottom" to "String" to ("margin-bottom"),
    "marginLeft" to "String" to ("margin-left"),
    "marginRight" to "String" to ("margin-right"),
    "marginTop" to "String" to ("margin-top"),
    "mark" to "String" to ("mark"),
    "markAfter" to "String" to ("mark-after"),
    "markBefore" to "String" to ("mark-before"),
    "marks" to "String" to ("marks"),
    "marqueeDirection" to "String" to ("marquee-direction"),
    "marqueePlayCount" to "String" to ("marquee-play-count"),
    "marqueeSpeed" to "String" to ("marquee-speed"),
    "marqueeStyle" to "String" to ("marquee-style"),
    "mask" to "String" to ("mask"),
    "maskType" to "String" to ("mask-type"),
    "maxHeight" to "String" to ("max-height"),
    "maxWidth" to "String" to ("max-width"),
    "minHeight" to "String" to ("min-height"),
    "minWidth" to "String" to ("min-width"),
    "navDown" to "String" to ("nav-down"),
    "navIndex" to "String" to ("nav-index"),
    "navLeft" to "String" to ("nav-left"),
    "navRight" to "String" to ("nav-right"),
    "navUp" to "String" to ("nav-up"),
    "objectFit" to "String" to ("object-fit"),
    "objectPosition" to "String" to ("object-position"),
    "opacity" to "String" to ("opacity"),
    "order" to "String" to ("order"),
    "orphans" to "String" to ("orphans"),
    "outline" to "String" to ("outline"),
    "outlineColor" to "String" to ("outline-color"),
    "outlineOffset" to "String" to ("outline-offset"),
    "outlineStyle" to "String" to ("outline-style"),
    "outlineWidth" to "String" to ("outline-width"),
    "overflowWrap" to "String" to ("overflow-wrap"),
    "overflowX" to "String" to ("overflow-x"),
    "overflowY" to "String" to ("overflow-y"),
    "padding" to "String" to ("padding"),
    "paddingBottom" to "String" to ("padding-bottom"),
    "paddingLeft" to "String" to ("padding-left"),
    "paddingRight" to "String" to ("padding-right"),
    "paddingTop" to "String" to ("padding-top"),
    "pageBreakAfter" to "String" to ("page-break-after"),
    "pageBreakBefore" to "String" to ("page-break-before"),
    "pageBreakInside" to "String" to ("page-break-inside"),
    "perspective" to "String" to ("perspective"),
    "perspectiveOrigin" to "String" to ("perspective-origin"),
    "phonemes" to "String" to ("phonemes"),
    "position" to "String" to ("position"),
    "quotes" to "String" to ("quotes"),
    "resize" to "String" to ("resize"),
    "rest" to "String" to ("rest"),
    "restAfter" to "String" to ("rest-after"),
    "restBefore" to "String" to ("rest-before"),
    "right" to "String" to ("right"),
    "tabSize" to "String" to ("tab-size"),
    "tableLayout" to "String" to ("table-layout"),
    "textAlign" to "String" to ("text-align"),
    "textAlignLast" to "String" to ("text-align-last"),
    "textCombineUpright" to "String" to ("text-combine-upright"),
    "textDecoration" to "String" to ("text-decoration"),
    "textDecorationColor" to "String" to ("text-decoration-color"),
    "textDecorationLine" to "String" to ("text-decoration-line"),
    "textDecorationStyle" to "String" to ("text-decoration-style"),
    "textIndent" to "String" to ("text-indent"),
    "textJustify" to "String" to ("text-justify"),
    "textOrientation" to "String" to ("text-orientation"),
    "textOverflow" to "String" to ("text-overflow"),
    "textShadow" to "String" to ("text-shadow"),
    "textTransform" to "String" to ("text-transform"),
    "textUnderlinePosition" to "String" to ("text-underline-position"),
    "top" to "String" to ("top"),
    "transform" to "String" to ("transform"),
    "transformOrigin" to "String" to ("transform-origin"),
    "transformStyle" to "String" to ("transform-style"),
    "transition" to "String" to ("transition"),
    "transitionDelay" to "String" to ("transition-delay"),
    "transitionDuration" to "String" to ("transition-duration"),
    "transitionProperty" to "String" to ("transition-property"),
    "transitionTimingFunction" to "String" to ("transition-timing-function"),
    "unicodeBidi" to "String" to ("unicode-bidi"),
    "verticalAlign" to "String" to ("vertical-align"),
    "visibility" to "String" to ("visibility"),
    "voiceBalance" to "String" to ("voice-balance"),
    "voiceDuration" to "String" to ("voice-duration"),
    "voicePitch" to "String" to ("voice-pitch"),
    "voicePitchRange" to "String" to ("voice-pitch-range"),
    "voiceRate" to "String" to ("voice-rate"),
    "voiceStress" to "String" to ("voice-stress"),
    "voiceVolume" to "String" to ("voice-volume"),
    "whiteSpace" to "String" to ("white-space"),
    "widows" to "String" to ("widows"),
    "width" to "String" to ("width"),
    "wordBreak" to "String" to ("word-break"),
    "wordSpacing" to "String" to ("word-spacing"),
    "wordWrap" to "String" to ("word-wrap"),
    "writingMode" to "String" to ("writing-mode"),
    "zIndex" to "String" to ("z-index"),
    "nodeValue" to "String" to "className" to "String" to ("class"),
    "id" to "String" to ("id"),
    "slot" to "String" to ("slot"),
    "accessKey" to "String" to ("accesskey"),
    "dir" to "String" to ("dir"),
    "draggable" to "Boolean" to ("draggable"),
    "hidden" to "Boolean" to ("hidden"),
    "lang" to "String" to ("lang"),
    "spellcheck" to "Boolean" to ("spellcheck"),
    "title" to "String" to ("title"),
    "translate" to "Boolean" to ("translate"),
    "download" to "String" to ("download"),
    "hreflang" to "String" to ("hreflang"),
    "ping" to "String" to ("ping"),
    "rel" to "String" to ("rel"),
    "shape" to "String" to ("shape"),
    "target" to "String" to ("target"),
    "align" to "String" to ("align"),
    "alt" to "String" to ("alt"),
    "code" to "String" to ("code"),
    "alt" to "String" to ("alt"),
    "coords" to "String" to ("coords"),
    "download" to "String" to ("download"),
    "ping" to "String" to ("ping"),
    "rel" to "String" to ("rel"),
    "shape" to "String" to ("shape"),
    "target" to "String" to ("target"),
    "crossOrigin" to "String" to ("crossorigin"),
    "autoplay" to "Boolean" to ("autoplay"),
    "buffered" to "String" to ("buffered"),
    "controls" to "Boolean" to ("controls"),
    "loop" to "Boolean" to ("loop"),
    "muted" to "Boolean" to ("muted"),
    "preload" to "String" to ("preload"),
    "src" to "String" to ("src"),
    "href" to "String" to ("href"),
    "target" to "String" to ("target"),
    "background" to "String" to ("background"),
    "autofocus" to "String" to ("autofocus"),
    "disabled" to "Boolean" to ("disabled"),
    "form" to "String" to ("form"),
    "formAction" to "String" to ("formaction"),
    "formEnctype" to "String" to ("formenctype"),
    "formMethod" to "String" to ("formmethod"),
    "formNoValidate" to "Boolean" to ("formnovalidate"),
    "formTarget" to "String" to ("formtarget"),
    "name" to "String" to ("name"),
    "type" to "String" to ("type"),
    "value" to "String" to ("value"),
    "height" to "Int" to ("height"),
    "width" to "Int" to ("width"),
    "align" to "String" to ("align"),
    "align" to "String" to ("align"),
    "span" to "Int" to ("span"),
    "value" to "String" to ("value"),
    "cite" to "String" to ("cite"),
    "dateTime" to "String" to ("datetime"),
    "open" to "Boolean" to ("open"),
    "open" to "Boolean" to ("open"),
    "height" to "String" to ("height"),
    "src" to "String" to ("src"),
    "type" to "String" to ("type"),
    "width" to "String" to ("width"),
    "disabled" to "Boolean" to ("disabled"),
    "form" to "String" to ("form"),
    "name" to "String" to ("name"),
    "color" to "String" to ("color"),
    "acceptCharset" to "String" to ("accept-charset"),
    "action" to "String" to ("action"),
    "autocomplete" to "String" to ("autocomplete"),
    "enctype" to "String" to ("enctype"),
    "method" to "String" to ("method"),
    "name" to "String" to ("name"),
    "noValidate" to "Boolean" to ("novalidate"),
    "target" to "String" to ("target"),
    "align" to "String" to ("align"),
    "color" to "String" to ("color"),
    "align" to "String" to ("align"),
    "allow" to "String" to ("allow"),
    "csp" to "String" to ("csp"),
    "height" to "String" to ("height"),
    "loading" to "String" to ("loading"),
    "name" to "String" to ("name"),
    "referrerpolicy" to "String" to ("referrerpolicy"),
    "sandbox" to "String" to ("sandbox"),
    "src" to "String" to ("src"),
    "srcdoc" to "String" to ("srcdoc"),
    "width" to "String" to ("width"),
    "align" to "String" to ("align"),
    "alt" to "String" to ("alt"),
    "border" to "String" to ("border"),
    "height" to "Int" to ("height"),
    "isMap" to "Boolean" to ("ismap"),
    "loading" to "String" to ("loading"),
    "referrerpolicy" to "String" to ("referrerpolicy"),
    "sizes" to "String" to ("sizes"),
    "src" to "String" to ("src"),
    "srcset" to "String" to ("srcset"),
    "useMap" to "String" to ("usemap"),
    "width" to "Int" to ("width"),
    "accept" to "String" to ("accept"),
    "alt" to "String" to ("alt"),
    "autocomplete" to "String" to ("autocomplete"),
    "autofocus" to "Boolean" to ("autofocus"),
    "checked" to "Boolean" to ("checked"),
    "dirName" to "String" to ("dirname"),
    "disabled" to "Boolean" to ("disabled"),
    "form" to "String" to ("form"),
    "formAction" to "String" to ("formaction"),
    "formEnctype" to "String" to ("formenctype"),
    "formMethod" to "String" to ("formmethod"),
    "formNoValidate" to "Boolean" to ("formnovalidate"),
    "formTarget" to "String" to ("formtarget"),
    "height" to "Int" to ("height"),
    "list" to "String" to ("list"),
    "max" to "String" to ("max"),
    "maxLength" to "Int" to ("maxlength"),
    "minLength" to "Int" to ("minlength"),
    "min" to "String" to ("min"),
    "multiple" to "Boolean" to ("multiple"),
    "name" to "String" to ("name"),
    "pattern" to "String" to ("pattern"),
    "placeholder" to "String" to ("placeholder"),
    "readOnly" to "Boolean" to ("readonly"),
    "required" to "Boolean" to ("required"),
    "size" to "Int" to ("size"),
    "src" to "String" to ("src"),
    "step" to "String" to ("step"),
    "type" to "String" to ("type"),
    "useMap" to "String" to ("usemap"),
    "value" to "String" to ("value"),
    "width" to "Int" to ("width"),
    "autofocus" to "Boolean" to ("autofocus"),
    "challenge" to "String" to ("challenge"),
    "disabled" to "Boolean" to ("disabled"),
    "form" to "String" to ("form"),
    "keytype" to "String" to ("keytype"),
    "name" to "String" to ("name"),
    "htmlFor" to "String" to ("for"),
    "form" to "String" to ("form"),
    "value" to "Int" to ("value"),
    "crossOrigin" to "String" to ("crossorigin"),
    "href" to "String" to ("href"),
    "hreflang" to "String" to ("hreflang"),
    "media" to "String" to ("media"),
    "referrerPolicy" to "String" to ("referrerpolicy"),
    "rel" to "String" to ("rel"),
    "sizes" to "String" to ("sizes"),
    "type" to "String" to ("type"),
    "name" to "String" to ("name"),
    "bgColor" to "String" to ("bgcolor"),
    "loop" to "Int" to ("loop"),
    "type" to "String" to ("type"),
    "content" to "String" to ("content"),
    "httpEquiv" to "String" to ("http-equiv"),
    "name" to "String" to ("name"),
    "form" to "String" to ("form"),
    "high" to "Double" to "high",
    "low" to "Double" to "low",
    "max" to "Double" to "max",
    "min" to "Double" to "min",
    "optimum" to "Double" to "optimum",
    "value" to "Double" to "value",
    "border" to "String" to ("border"),
    "data" to "String" to ("data"),
    "form" to "String" to ("form"),
    "height" to "String" to ("height"),
    "name" to "String" to ("name"),
    "type" to "String" to ("type"),
    "useMap" to "String" to ("usemap"),
    "width" to "String" to ("width"),
    "reversed" to "Boolean" to ("reversed"),
    "start" to "Int" to ("start"),
    "type" to "String" to ("type"),
    "disabled" to "Boolean" to ("disabled"),
    "label" to "String" to ("label"),
    "disabled" to "Boolean" to ("disabled"),
    "label" to "String" to ("label"),
    "selected" to "Boolean" to ("selected"),
    "value" to "String" to ("value"),
    "htmlFor" to "String" to ("for"),
    "form" to "String" to ("form"),
    "name" to "String" to ("name"),
    "name" to "String" to ("name"),
    "value" to "String" to ("value"),
    "form" to "String" to ("form"),
    "max" to "Double" to "max",
    "value" to "Double" to "value",
    "cite" to "String" to ("cite"),
    "async" to "Boolean" to ("async"),
    "charset" to "String" to ("charset"),
    "crossOrigin" to "String" to "crossorigin",
    "defer" to "Boolean" to ("defer"),
    "integrity" to "String" to ("integrity"),
    "referrerPolicy" to "String" to ("referrerpolicy"),
    "src" to "String" to ("src"),
    "type" to "String" to ("type"),
    "autocomplete" to "String" to ("autocomplete"),
    "autofocus" to "Boolean" to ("autofocus"),
    "disabled" to "Boolean" to ("disabled"),
    "form" to "String" to ("form"),
    "multiple" to "Boolean" to ("multiple"),
    "name" to "String" to ("name"),
    "required" to "Boolean" to ("required"),
    "size" to "Int" to ("size"),
    "media" to "String" to ("media"),
    "sizes" to "String" to ("sizes"),
    "src" to "String" to ("src"),
    "srcset" to "String" to ("srcset"),
    "type" to "String" to ("type"),
    "media" to "String" to ("media"),
    "type" to "String" to ("type"),
    "align" to "String" to ("align"),
    "border" to "String" to ("border"),
    "summary" to "String" to ("summary"),
    "align" to "String" to ("align"),
    "align" to "String" to ("align"),
    "colSpan" to "Int" to ("colspan"),
    "headers" to "String" to ("headers"),
    "rowSpan" to "Int" to ("rowspan"),
    "autocomplete" to "String" to ("autocomplete"),
    "autofocus" to "Boolean" to ("autofocus"),
    "cols" to "Int" to ("cols"),
    "dirName" to "String" to ("dirname"),
    "disabled" to "Boolean" to ("disabled"),
    "form" to "String" to ("form"),
    "inputMode" to "String" to ("inputmode"),
    "maxLength" to "Int" to ("maxlength"),
    "minLength" to "Int" to ("minlength"),
    "name" to "String" to ("name"),
    "placeholder" to "String" to ("placeholder"),
    "readOnly" to "Boolean" to ("readonly"),
    "required" to "Boolean" to ("required"),
    "rows" to "Int" to ("rows"),
    "wrap" to "String" to ("wrap"),
    "value" to "String" to "value",
    "dateTime" to "String" to ("datetime"),
    "align" to "String" to ("align"),
    "default" to "Boolean" to ("default"),
    "kind" to "String" to ("kind"),
    "label" to "String" to ("label"),
    "src" to "String" to ("src"),
    "srclang" to "String" to ("srclang"),
    "buffered" to "String" to ("buffered"),
    "height" to "Int" to ("height"),
    "playsInline" to "Boolean" to ("playsinline"),
    "poster" to "String" to ("poster"),
    "width" to "Int" to ("width"),
)

css.forEach {  (js, css) ->
    println("expect var CSSStyleDeclarationHandle.$js: String")
}
html.forEach {  (jsAndType, css) ->
    val (js, type) = jsAndType
    println("expect var CSSStyleDeclarationHandle.$js: $type")
}