package com.lightningkite.mppexampleapp

import com.lightningkite.kiteui.models.*

actual object Resources {
    actual val audioTaunt: AudioResource = AudioResource("audioTaunt", "mp3")
    actual val fontsGoldman: Font = fontFromFamilyInfo(normal = "Goldman-Regular", italic = null, bold = "Goldman-Bold", boldItalic = null)  // Font(name=fontsGoldman, normal=SubFont(source=/Users/jivie/Projects/kiteui/example-app/src/commonMain/resources/fonts/goldman/normal.ttf, relativeFile=fonts/goldman/normal.ttf, fontSuperFamily=, fontFamily=Goldman, fontSubFamily=Regular, postScriptName=Goldman-Regular), bold=SubFont(source=/Users/jivie/Projects/kiteui/example-app/src/commonMain/resources/fonts/goldman/bold.ttf, relativeFile=fonts/goldman/bold.ttf, fontSuperFamily=, fontFamily=Goldman, fontSubFamily=Bold, postScriptName=Goldman-Bold), italic=null, boldItalic=null)
    actual val fontsMontserrat: Font = fontFromFamilyInfo(normal = "Montserrat-Regular", italic = "Montserrat-Italic", bold = "Montserrat-Bold", boldItalic = "Montserrat-BoldItalic")  // Font(name=fontsMontserrat, normal=SubFont(source=/Users/jivie/Projects/kiteui/example-app/src/commonMain/resources/fonts/montserrat/normal.ttf, relativeFile=fonts/montserrat/normal.ttf, fontSuperFamily=, fontFamily=Montserrat, fontSubFamily=Regular, postScriptName=Montserrat-Regular), bold=SubFont(source=/Users/jivie/Projects/kiteui/example-app/src/commonMain/resources/fonts/montserrat/bold.ttf, relativeFile=fonts/montserrat/bold.ttf, fontSuperFamily=, fontFamily=Montserrat, fontSubFamily=Bold, postScriptName=Montserrat-Bold), italic=SubFont(source=/Users/jivie/Projects/kiteui/example-app/src/commonMain/resources/fonts/montserrat/italic.ttf, relativeFile=fonts/montserrat/italic.ttf, fontSuperFamily=, fontFamily=Montserrat, fontSubFamily=Italic, postScriptName=Montserrat-Italic), boldItalic=SubFont(source=/Users/jivie/Projects/kiteui/example-app/src/commonMain/resources/fonts/montserrat/bold-italic.ttf, relativeFile=fonts/montserrat/bold-italic.ttf, fontSuperFamily=, fontFamily=Montserrat, fontSubFamily=Bold Italic, postScriptName=Montserrat-BoldItalic))
    actual val fontsRoboto: Font = fontFromFamilyInfo(normal = "Roboto-Regular", italic = "Roboto-Italic", bold = "Roboto-Bold", boldItalic = "Roboto-BoldItalic")  // Font(name=fontsRoboto, normal=SubFont(source=/Users/jivie/Projects/kiteui/example-app/src/commonMain/resources/fonts/roboto/normal.ttf, relativeFile=fonts/roboto/normal.ttf, fontSuperFamily=, fontFamily=Roboto, fontSubFamily=Regular, postScriptName=Roboto-Regular), bold=SubFont(source=/Users/jivie/Projects/kiteui/example-app/src/commonMain/resources/fonts/roboto/bold.ttf, relativeFile=fonts/roboto/bold.ttf, fontSuperFamily=, fontFamily=Roboto, fontSubFamily=Bold, postScriptName=Roboto-Bold), italic=SubFont(source=/Users/jivie/Projects/kiteui/example-app/src/commonMain/resources/fonts/roboto/italic.ttf, relativeFile=fonts/roboto/italic.ttf, fontSuperFamily=, fontFamily=Roboto, fontSubFamily=Italic, postScriptName=Roboto-Italic), boldItalic=SubFont(source=/Users/jivie/Projects/kiteui/example-app/src/commonMain/resources/fonts/roboto/bold-italic.ttf, relativeFile=fonts/roboto/bold-italic.ttf, fontSuperFamily=, fontFamily=Roboto, fontSubFamily=Bold Italic, postScriptName=Roboto-BoldItalic))
    actual val fontsRobotoLight: Font = fontFromFamilyInfo(normal = "Roboto-Light", italic = null, bold = null, boldItalic = null)  // Font(name=fontsRobotoLight, normal=SubFont(source=/Users/jivie/Projects/kiteui/example-app/src/commonMain/resources/fonts/roboto/light.ttf, relativeFile=fonts/roboto/light.ttf, fontSuperFamily=Roboto, fontFamily=Roboto Light, fontSubFamily=Regular, postScriptName=Roboto-Light), bold=null, italic=null, boldItalic=null)
    actual val fontsRobotoLightItalic: Font = fontFromFamilyInfo(normal = "Roboto-LightItalic", italic = null, bold = null, boldItalic = null)  // Font(name=fontsRobotoLightItalic, normal=SubFont(source=/Users/jivie/Projects/kiteui/example-app/src/commonMain/resources/fonts/roboto/light-Italic.ttf, relativeFile=fonts/roboto/light-Italic.ttf, fontSuperFamily=Roboto, fontFamily=Roboto Light, fontSubFamily=Italic, postScriptName=Roboto-LightItalic), bold=null, italic=null, boldItalic=null)
    actual val imagesMammoth: ImageResource = ImageResource("imagesMammoth")
    actual val imagesSolera: ImageResource = ImageResource("imagesSolera")
    actual val videoBack: VideoResource = VideoResource("videoBack", "mp4")
}